version: "3"
services:
  client:
    build: ./client/
  server:
    build: ./server/
  mongodb:
    image: mongo
    container_name: "mongodb"
  proxy:
    build: ./proxy/
    ports:
      - "8000:80"
