version: "3"
services:
  client:
    build: ./client/
    volumes:
      - ./client/src:/usr/src/app/src
  server:
    build: ./server/
    volumes:
      - ./server/src:/usr/src/app/src
  mongodb:
    image: mongo
    container_name: "mongodb"
  proxy:
    build: ./proxy/
    ports:
      - "3000:80"
